---
title: "Sust. & CE"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    horizontal_layout: scroll
    runtime: shiny
    theme: sandstone
    highlight: zenburn
    logo: "/Users/fevegag/OneDrive/Desarrollo RStudio/Sust&CEGrids/Sust-CEGrids/images/enel_white_small.png"
    storyboard: true
    social: [ "linkedin", "twitter","menu" ]
---

```{r setup, include=FALSE}

library(flexdashboard)
library (haven)
library(ggplot2)
library(plotly)
library(dplyr)
library(survey)
library(questionr)
library(knitr)

#Path Macbook Felipe Datasets proyectos
#path = "/Users/fevegag/Municipalidad de Las Condes/DECOMCloud - Documentos/Planificación Social y Estudios/Estudios/EN TRABAJO/2020/20200814 CENSO SOCIAL LAS CONDES 2020/"

```

Sidebar {.sidebar data-width=100}
=====================================
***
<p align="left"><font size=3><b><a href="https://fevegag.github.io/Sust-CEGrids/" target="_blank">INICIO</a></b></font></p>


Seguridad Energética en Campamentos {data-navmenu="Energy Poverty"}
=====================================  

Inclusión Energética {data-navmenu="Energy Poverty"}
=====================================  

Formación Instaladores Eléctricos Domciliarios {data-navmenu="Social and Economic Development"}
=====================================  

Educando con Energía ENEL CEO {data-navmenu="Education"}
=====================================  

Comunidad Circular {data-navmenu="Social and Economic Development"}
=====================================  

Eco-Carpintería (formación de oficios circulares) {data-navmenu="Circular Economy"}
=====================================  

Sitios de Construcción Sostenible en Dx {data-navmenu="Circular Economy"}
=====================================  

Cortometraje Ciclos Vitales {data-navmenu="Cambio climático"}
=====================================  

Vinculación Servicios Ecosistémicos {data-navmenu="Environmental, Nature & Biodiversity"}
=====================================  

Open Power to Art  {data-navmenu="Community Support"}
=====================================  


Talleres {data-orientation=rows}
=====================================

<iframe title="Dashboard Talleres Sust. and CE - Panel" width="100%" height="100%" src="https://app.powerbi.com/reportEmbed?reportId=f959ece7-07b0-4e62-984d-27b2f50c9a6b&autoAuth=true&ctid=d539d4bf-5610-471a-afc2-1c76685cfefa" frameborder="0" allowFullScreen="true"></iframe>